language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - php tests/console doctrine:database:create --env=travis
  - php tests/console doctrine:schema:create --env=travis
  - php tests/console doctrine:fixtures:load --env=travis --append

env:
  - SYMFONY__TEST_USER=admin

script: phpunit