id:				default
name:			Default Theme
url:			~
author: 		~
author_url: 	~
description: 	~
version: 		1.0
license: 		GNU General Public License v2 or later
license_url: 	http://www.gnu.org/licenses/gpl-2.0.html

widget_positions:
  - 'position-1'
  - 'position-2'