# support for dynamic frontend routing
_drafterbit_frontend:
    resource: .
    type: frontend

_drafterbit_system:
    resource: "@DrafterbitSystemBundle/Resources/config/routing.yml"

_drafterbit_file:
    resource: "@DrafterbitFileBundle/Resources/config/routing.yml"

_drafterbit_page:
    resource: "@DrafterbitPageBundle/Resources/config/routing.yml"

_drafterbit_blog:
    resource: "@DrafterbitBlogBundle/Resources/config/routing.yml"

_drafterbit_user:
    resource: "@DrafterbitUserBundle/Resources/config/routing/routing.yml"

_drafterbit_user_security:
    resource: "@DrafterbitUserBundle/Resources/config/routing/security.xml"

_drafterbit_user_profile:
    resource: "@DrafterbitUserBundle/Resources/config/routing/profile.xml"

_drafterbit_user_register:
    resource: "@DrafterbitUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

_drafterbit_user_resetting:
    resource: "@DrafterbitUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

_drafterbit_user_change_password:
    resource: "@DrafterbitUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

#_drafterbit_user_group:
#    resource: "@DrafterbitUserBundle/Resources/config/routing/group.xml"
#    prefix: /group
