system:
    navigation:
        setting:
            label: Setting
            children:
                general:
                    label: General
                    route: drafterbit_system_setting_general
                theme:
                    label: Theme
                    route: drafterbit_system_setting_theme
        system:
            label: System
            children:
                log:
                    label: Log
                    route: drafterbit_system_log
                cache:
                    label: Cache
                    route: drafterbit_system_cache
