# support for dynamic frontend routing
_drafterbit_frontend:
    resource: .
    type: frontend

drafterbit_system:
    resource: "@SystemBundle/Controller/"
    type:     annotation

_drafterbit_user:
    resource: "@UserBundle/Resources/config/routing/routing.yml"

_drafterbit_user_security:
    resource: "@UserBundle/Resources/config/routing/security.xml"

_drafterbit_file:
    resource: "@FileBundle/Resources/config/routing.yml"

_drafterbit_page:
    resource: "@PageBundle/Resources/config/routing.yml"