# support for dynamic frontend routing
_dt_frontend:
    resource: .
    type: frontend

dt_system:
    resource: "@SystemBundle/Controller/"
    type:     annotation

_dt_user:
    resource: "@UserBundle/Resources/config/routing/routing.yml"

_dt_user_security:
    resource: "@UserBundle/Resources/config/routing/security.xml"

_dt_file:
    resource: "@FileBundle/Resources/config/routing.yml"

_dt_page:
    resource: "@PageBundle/Resources/config/routing.yml"