imports:
    - { resource: assets/assets.yml }
    - { resource: @PageBundle/Resources/config/system/navigation.yml }
    - { resource: @FileBundle/Resources/config/system/navigation.yml }
    - { resource: @UserBundle/Resources/config/system/navigation.yml }
    - { resource: @SystemBundle/Resources/config/navigation.yml }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Drafterbit\Bundle\UserBundle\Entity\User
    group:
        group_class: Drafterbit\Bundle\UserBundle\Entity\Group