id:				prologue
name:			Prologue
url:			http://html5up.net/prologue
author: 		html5up
author_url: 	http://html5up.net
description: 	"A free, fully responsive site template by HTML5 UP"
version: 		1.0
license: 		GNU General Public License v2 or later
license_url: 	http://www.gnu.org/licenses/gpl-2.0.html
